### ISSUE TITLE
không thể run được test verify trên FF 

### ISSUE THREAD

**Issue by vietlq4** [vuthelinh/selenium-vietnam-training-course#1]
sử dụng maven 3.5
serenity 1.5
FF 53.0

khi run command "mvn test verify " bị fail chỉ bật được browser lên không làm được thao tác gì 
Error message : Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project serenity-cucumber: There are test failures.

**Comment by vuthelinh** [comment]
Với FF 53 cần sử dụng gecko drvier và truyền thêm thông số sau vào dòng lệnh
mvn test verify -Dwebdriver.driver=firefox -Dwebdriver.gecko.driver=E:\geckodriver.exe

**Comment by vuthelinh** [comment]
Cách 2: Mở file serenity.properties và điền thông tin sau
`# Define the default driver`
`webdriver.driver=firefox`
`webdriver.gecko.driver=E:\geckodriver.exe`

**Comment by vuthelinh** [comment]
Để chạy với FF
> mvn test verify -Dwebdriver.driver=firefox -Dwebdriver.gecko.driver=E:\geckodriver.exe

Để chạy với Chrome
> mvn test verify -Dwebdriver.driver=chrome -Dwebdriver.chrome .driver=E:\chromedriver.exe

Để chạy với PhantomJS
> mvn test verify -Dwebdriver.driver=phantomjs

Để chạy với IE
> mvn test verify -Dwebdriver.driver=iexplorer -Dwebdriver.ie.driver=E:\IEDriverServer.exe

Để chạy với Edge
> mvn test verify -Dwebdriver.driver=iexplorer -Dwebdriver.edge.driver=E:\MicrosoftWebDriver.exe

**To avoid such errors, you need to disable some setting in Edge browser. To do that go to 
Open Browser -> Settings -> View advanced settings
Disable all settings.**

**Comment by vuthelinh** [comment]
http://www.automationtestinghub.com/selenium-3-launch-microsoft-edge-with-microsoftwebdriver/
https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/
