### ISSUE TITLE
Get Xpath in Table (tr/td/span) ?

### ISSUE THREAD

**Issue by nguyendinhthuan789** [vuthelinh/selenium-vietnam-training-course#16]
I cannot get xpath with image below, please help me. Tks
![46a4f4125dac5bc27418b923a8af4d6f81248f2c833f55a0b4 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/24774362/31110160-3964e17e-a82f-11e7-8d20-6f17ab44df16.png)

**Comment by vuthelinh** [comment]
@nguyendinhthuan789 Em đếm xem cái xpath đó bằng mấy. Anh e rằng xpath kiểu này sẽ tồn tại nhiều hơn một giá trị. 

Thay vào đó em nên lấy theo text: Phần tiếng Nhật em copy bị cái text bên phải vào.

Ví dụ: `//th[text()=' tiếng nhật bó tay luôn']/following-sibling::td/span`

**Comment by nguyendinhthuan789** [comment]
@vuthelinh  : em thử theo cách của anh thì ntn : //th[text()='税抜価格']/following-sibling::td/span
em run nó miss

**Comment by vuthelinh** [comment]
Vấn đề nó không nằm ở việc locate element nữa. Debug chạy chậm lại kịch bản để tìm nguyên nhân
