### ISSUE TITLE
Cách quản lý WebDriver hiệu quả trong một site Ecommerce

### ISSUE THREAD

**Issue by nguyendinhthuan789** [vuthelinh/selenium-vietnam-training-course#17]

**Comment by vuthelinh** [comment]
@nguyendinhthuan789 Bạn hãy mô tả cụ thể và rõ ràng hơn điều bạn muốn làm là gì ?

**Comment by nguyendinhthuan789** [comment]
Hi anh @vuthelinh  
Tức là khi mình khởi tạo driver ở các class parent và class kế thừa.. á a. làm sao để mình không phải khởi tạo nhiều lần .
Tks

**Comment by vuthelinh** [comment]
E cần phải có code mẫu. Để xem kỹ năng viết code của e ra sao. Đây ko phải common issue.

**Comment by nguyendinhthuan789** [comment]
Hi anh @vuthelinh 
EM làm 1 cái common Wait ntn :
![wait common](https://user-images.githubusercontent.com/24774362/31180335-8f55f8ec-a948-11e7-8e99-d1b461cdaa75.png)

Em tạo 1 class gọi ham waitUntilToBeClickAble nhưng ko goi dc:
![call common](https://user-images.githubusercontent.com/24774362/31180374-acd4e22a-a948-11e7-8e11-cae609f71eeb.png)

tks

**Comment by vuthelinh** [comment]
Ko thấy chỗ nào khởi tạo driver cả

**Comment by nguyendinhthuan789** [comment]
Hi anh @vuthelinh 
em khởi tạo bằng cách: WaitUtility wait=new WaitUtility(driver);
vậy ko dc hả anh!
em đang bí chổ này anh help em vs

**Comment by nguyendinhthuan789** [comment]
Hi anh @vuthelinh 
em change class call waitUntilToBeClickAble  ntn:
![call common](https://user-images.githubusercontent.com/24774362/31182227-79df5a3a-a94d-11e7-9c0b-36f5d4463681.png)
tks

**Comment by vuthelinh** [comment]
Em cần khởi tạo driver bên ngoài trước rồi mới dùng nó để truyền vào các class có liên quan. Em khởi tạo bên trong các class thì làm sao nó có thể giữ được các session để truyền ra ngoài và truyền sang các class khác được.
