### ISSUE TITLE
Làm sao để link file feature với file source code liên quan 

### ISSUE THREAD

**Issue by AnnaPhuong** [vuthelinh/selenium-vietnam-training-course#20]
Hiện tại em phải phân tích code để hiểu logic rồi viết các scenario. Em muốn hỏi có cách nào để em có thể tracking scenario or file feature này thì liên quan tới class code nào không ạ?

**Comment by vuthelinh** [comment]
Từ file feature. Chọn một dòng bất kỳ. Ấn F3. Nó sẽ find Steps tương ứng trong class code.

Còn vấn để tracking hay quản lý. Do em sắp xếp các package thế nào cho hợp lý. Để khi nhìn dễ nhận thấy sự liên quan.
