### ISSUE TITLE
Lỗi khi chạy Run TestNG

### ISSUE THREAD

**Issue by linhptt** [vuthelinh/selenium-vietnam-training-course#21]
Mình mới viết 1 đoạn code ngắn đơn giản để mở FF lên nhưng khi run thì bị lỗi này, mọi người giúp mình với nhé:

[Utils] Problem creating output directory C:\Users\Linhptt3\workspace\AI_2\test-output\old\Default suite
[Utils] Attempting to create C:\Users\Linhptt3\workspace\AI_2\test-output\old\Default suite\toc.html
[Utils]   Directory C:\Users\Linhptt3\workspace\AI_2\test-output\old\Default suite exists: true
[Utils] Problem creating output directory C:\Users\Linhptt3\workspace\AI_2\test-output\old\Default suite
[Utils] Attempting to create C:\Users\Linhptt3\workspace\AI_2\test-output\old\Default suite\Default test.properties
[Utils]   Directory C:\Users\Linhptt3\workspace\AI_2\test-output\old\Default suite exists: true

**Comment by caodangtinh** [comment]
@linhptt : Bạn có thể cho mình xem đoạn code (bao gồm cả đoạn khai báo WebDriver), mình nghĩ vấn dề do việc khai báo trùng WebDriver

**Comment by linhptt** [comment]
đây bạn: 
package MBOT;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class NhapCH {
	public static WebDriver driver;
	public static String baseUrl;
	
	@BeforeTest
	public void before(){
		
		System.setProperty("webdriver.ie.driver", "C:\\Driver EXE\\IEDriverServer.exe");
		driver=new FirefoxDriver();
		baseUrl="file:///D:/Project/AI_Voice/Tong%20hop%20cau%2 0hoi/MB%20Bank%20Demo_v2/MB%20Bank%20Demo.html";
	//	driver.get(baseUrl);
		}
	@Test
	 public void openWeb(){
	driver.get(baseUrl);
	
	} 
		

}

**Comment by linhptt** [comment]
Chính xác thì chỗ Error log nó ghi như này bạn ạ:
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.gecko.driver system property;

**Comment by vuthelinh** [comment]
@linhptt 
Bạn sửa lại tên thư mục `Driver EXE` thành `DriverEXE`. và thử lại

**Comment by linhptt** [comment]
Chỗ Driver EXE mình thử bỏ đi thì kết quả vẫn thế bạn ạ:

package MBOT;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class NhapCH {
	public static WebDriver driver;
	public static String baseUrl;
	
	@BeforeTest
	public void before(){
		
		driver=new FirefoxDriver();
		baseUrl="file:///D:/Project/AI_Voice/Tong%20hop%20cau%2 0hoi/MB%20Bank%20Demo_v2/MB%20Bank%20Demo.html";
	//	driver.get(baseUrl);
		}
	@Test
	 public void openWeb(){
	driver.get(baseUrl);

	} 
		

}

**Comment by vuthelinh** [comment]
@linhptt Giữ nguyên code cũ và SỬA LẠI TÊN THƯ MỤC không phải xóa nó đi.
Xóa cái thư mục `test-output`

**Comment by vuthelinh** [comment]
```
@BeforeTest
public void before(){
        System.setProperty("webdriver.gecko.driver", ".\\driver\\geckodriver.exe");
	driver=new FirefoxDriver();
	baseUrl="xxxxxx";
	}

@Test
 public void openWeb(){
     driver.get(baseUrl);
} 
```
Bạn tạo một thư mục tên là driver trong thư mục dự án và download geckodriver.exe  bỏ vào đó.

Còn nếu muốn chạy với trình duyệt IE. Thì download cái IEDriverServer bỏ vào thư mục driver và chạy đoạn code này

```
public void before(){
        System.setProperty("webdriver.ie.driver", ".\\driver\\IEDriverServer.exe");
	driver=new InternetExplorerDriver();
	baseUrl="xxxxxx";
	}

@Test
 public void openWeb(){
     driver.get(baseUrl);
} 
```

**Comment by linhptt** [comment]
Mình đang muốn chạy FF bạn ạ, mình sửa thành như này được ko:

package MBOT;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class NhapCH {
	public static WebDriver driver;
	public static String baseUrl;
	
	@BeforeTest
	public void before(){
		
		System.setProperty("webdriver.gecko.driver", "C:\\Program Files (x86)\\Mozilla Firefox\firefox.exe");
		driver=new FirefoxDriver();
		baseUrl="file:///D:/Project/AI_Voice/Tong%20hop%20cau%2 0hoi/MB%20Bank%20Demo_v2/MB%20Bank%20Demo.html";
		}
	@Test
	 public void openWeb(){
	driver.get(baseUrl);

	} 
	
}

**Comment by vuthelinh** [comment]
@linhptt 
Ad nghĩ là không? Nó phải trở tới bản driver binary. không phải file chạy của Firefox. Bạn nên tham khảo đoạn code phía trên

**Comment by caodangtinh** [comment]
@linhptt : mục đích của đoạn setProperty là bạn đang đang set cho property webdriver.gecko.driver trỏ đến đường dẫn của gecko driver, như vậy giá trị của nó phải trỏ đến file geckodriver.exe, ở ví dụ bên trên a @vuthelinh  đang để file geckodriver.exe trong thư mục driver cùng thư mục dự án nên đường dẫn sẽ là .\\driver\\geckodriver.exe.
Nhưng theo mình để thuận tiện nhất thì bạn có 2 cách : 

1. Bạn thêm config webdriver.gecko.driver=PATH_TO_GECKO vào file senerity.properties
2.  Lúc chạy chương trình bằng command line bạn truyền tham số -Dwebdriver.gecko.driver = PATH_TO_GECKO khi chạy

**Comment by vuthelinh** [comment]
@caodangtinh Bạn ấy mới đang học chạy kịch bản auto với TestNG. Không có liên quan tới serenity trong chương trình học của lớp đào tạo đâu em

**Comment by linhptt** [comment]
Được rồi các bạn ạ, do cái gecko của mình bản cũ quá =))
Cảm ơn các bạn nhiều nhiều nhé
