### ISSUE TITLE
Nhờ Review code

### ISSUE THREAD

**Issue by interpol2006** [vuthelinh/selenium-vietnam-training-course#22]

**Comment by vuthelinh** [comment]
1. Đôi hết các WebElement  thành WebElementFacade. Nếu không sẽ không tận dụng được cái tính năng mới có trong PageObject cái được extends

2. Không phải tất cả các class ở phần Page đều cần giá trị `@DefaultUrl("http://xxx.yyy.review")`

3. Không nên sử dụng `Assert.assertEquals` trong phần Page. Nó nên được sử dụng ở phần Def Steps vì nếu kết quả fail nó sẽ dừng toàn bộ các Steps phía sau. Nó chỉ nên đặt phía cuối của mỗi Scenario. Là bước cuối cùng để check kết quả outcome

4. Thay vì dùng `getDriver().navigate().to("http://stage2.dreamcheaper.review/");` thì nên dùng `open();`
-- còn tiếp --

**Comment by vuthelinh** [comment]
`if (cashback_option.getAttribute("value") == "#")`
Nếu là so sánh String thì dùng equal thay vì == ( đây là toán tử so sánh của kiểu boolean)

**Comment by vuthelinh** [comment]
6. `float included_tax_in_eur = 0` nên để là `float included_tax_in_eur = 0.0f`

**Comment by vuthelinh** [comment]
```
	public float get_included_tax()
	{
		float included_tax_in_eur = 0  ;
		float gross = get_dc_purchase_price_in_eur();
		
		if (included_tax_option.getAttribute("value") == "#")
		{
			included_tax_in_eur = Float.parseFloat(includedtaxField.getAttribute("value"));
		}
		else
		{
			included_tax_in_eur = gross*Float.parseFloat(includedtaxField.getAttribute("value"));
		}
		return included_tax_in_eur;
}
```

Thì nên là 
```
public float get_included_tax(){
  float included_tax_in_eur = 0.0f  ;
  float gross = get_dc_purchase_price_in_eur();
		
	if ("#".equals( included_tax_option.getAttribute("value") )
 		return Float.parseFloat(includedtaxField.getAttribute("value"));
	else
		return gross*Float.parseFloat(includedtaxField.getAttribute("value"));
}
```

**Comment by vuthelinh** [comment]
8. `Affiliate_earnings = (Affiliate + freenight)/100*(gross_cost - included_tax - freenight_used)`

Đối với các tổ hợp nhân và chia. Để cho rõ ràng thì nên đặt dâu ưu tiên
Hoặc
`Affiliate_earnings = ((Affiliate + freenight)/100*)(gross_cost - included_tax - freenight_used)`
Hoặc
`Affiliate_earnings = (Affiliate + freenight)/(100*(gross_cost - included_tax - freenight_used))`
