### ISSUE TITLE
Example mô hình POm trong framework

### ISSUE THREAD

**Issue by nguyendinhthuan789** [vuthelinh/selenium-vietnam-training-course#24]
Hi all, chả là em đang build 1 project theo mẫu sau:
1 packge chứ ui và action method
1 pcakge common,
1 package test
1 package parse json
Làm xong thì ko match vs POM model ai đó example chuẩn em tham khảo vs ạ : thanks

**Comment by caodangtinh** [comment]
@nguyendinhthuan789 : bạn có thể attach project hoặc tạo repo sau đó commit lên mình có thể check giúp

**Comment by nguyendinhthuan789** [comment]
@caodangtinh : bạn có skype send mình share cho tiện :)

**Comment by caodangtinh** [comment]
bạn send mail nhé , gmail của mình là caodangtinh@gmail.com

**Comment by nguyendinhthuan789** [comment]
@caodangtinh : mình add bạn vào git rùi. bạn ktra cái Radley_007 nha
