### ISSUE TITLE
Không xác định được locator

### ISSUE THREAD

**Issue by linhptt** [vuthelinh/selenium-vietnam-training-course#25]
HI all
Mình cần xác định locator để đăng nhập vào web, nhưng các thông tin đều để động không biết xác định kiểu gì, các bạn xem giúp mình với nhé. Đây là kết quả mình lấy từ Firebug:

<input id="gwt-uid-6" class="v-textfield v-widget login-username v-textfield-login-username v-textfield-required v-required" type="password" aria-labelledby="gwt-uid-5" aria-required="true" tabindex="0" style="position: relative; top: 0px; left: 59px;">

=> Cái ID thì động ko lấy được rồi, mình thử cái class cũng ko được, ko biết lấy như nào luôn

![3](https://user-images.githubusercontent.com/22230468/31379672-26695104-add9-11e7-9f8f-552b7730649a.jpg)

**Comment by vuthelinh** [comment]
@linhptt 
Có rất nhiều cách để xác định địa chỉ một phần tử trên trang web. Nếu xác định nó theo ID không khả thi thì bạn lấy nó theo xpath. Xác định vị trí của nó thông qua một phần tử cố định khác.

Hoặc có thể xác định nó theo các css như dựa vào class...

**Comment by linhptt** [comment]
Vấn đề là mình đã thử mà ko được ấy
Mình thử xác định theo class là:  driver.findElement(By.xpath("//a[contains(@class,'login-username')]"))

=> Vẫn bị báo là Unable to locate element: //a[contains(@class,'login-username')]

**Comment by vuthelinh** [comment]
Không được nghĩa là mình sai chỗ nào đó.
Trong hình của em làm gì có thẻ nào là thẻ a. là thẻ div mà. Class sao lại viết hoa chữ C.

Thử với cái này xem.
`//div[contains(@class,'login-username')]`

**Comment by linhptt** [comment]
Vẫn ko được anh ah, nó báo là:

Unable to locate element: //div[contains(@class,'login-username')]

Chữ C viết hoa là do copy bị tự chuyển đấy

**Comment by vuthelinh** [comment]
Em ấn F12 trên trình duyệt và sử dụng chức năng find Element. Điền Xpath vào kiểm tra xem nó có tìm thấy trên web page không?

Còn trong quá trình chạy nó báo như thế thì có thể là e không biết cách xử lý wait.

**Comment by linhptt** [comment]
Đúng là do e chưa xử lý wait, thêm vào cái được luôn
Cảm ơn anh nhiều nhiều nhé : +1:

**Comment by vuthelinh** [comment]
Hãy like và chia sẻ về kênh thông tin fan page của anh tới bạn bè nhé. Thanks

**Comment by linhptt** [comment]
OK anh
