### ISSUE TITLE
Read file json common

### ISSUE THREAD

**Issue by nguyendinhthuan789** [vuthelinh/selenium-vietnam-training-course#33]
Hi all:
mình làm 1 method read json ntn:
public JSONObject parseContent(String dir) throws Exception {
			File file = new File(System.getProperty("user.dir") + dir);
			String content = FileUtils.readFileToString(file, "utf-8");
			return new JSONObject(content);
		}

xong qua main gọi:
public static void main(String[] args) {
			try{
				JsonRead read=new JsonRead();
				read.parseContent("lib/abc.json");
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
		}

Error path.. mọi người help cs ạ
Thanks

**Comment by caodangtinh** [comment]
bạn có thể cho mình xem cấu trúc thư mục và full log error được không, như vậy sẽ dễ dàng tìm bug hơn

**Comment by nguyendinhthuan789** [comment]
@Thank @caodangtinh  mình sửa dc rùi
