### ISSUE TITLE
Use Data-Driven from file excel in Selenium 2.0

### ISSUE THREAD

**Issue by NTHang** [vuthelinh/selenium-vietnam-training-course#34]
Hi all, Em đang gặp phải vấn đề chưa rõ mong mọi người giúp đỡ ạ.
Em đang kiểm tra trang register của trang: http://demoqa.com/registration/. Em muốn hỏi về việc radio, checkbox, dropdown sẽ được lấy từ file excel sẽ là giá trị mà mình đã nhập ạ. Trường hợp bỏ trống nhiều trường bắt buộc, nhiều trường thông tin cùng báo thì sẽ thông báo từng trường như thế nào ạ.
Thanks all!

**Comment by vuthelinh** [comment]
Em viết 7 cái hàm kiểm tra 7 dòng text kia đang present. Sau khi điền dữ liệu cho một elemetn nào đó thì đổi cái hàm kiểm tử từ Present tương ứng thành notPresent.
