### ISSUE TITLE
#Lỗi: table view is not available with this format trong selenium 2.9.1

### ISSUE THREAD

**Issue by HaiYen101** [vuthelinh/selenium-vietnam-training-course#39]
Anh cho em hỏi ạ.
Em vẫn đang dùng Selenium bình thường nhưng tắt đi vào lại lại không không dùng được và báo là "table view is not available with this format " anh giúp em sửa lỗi được không ạ.
Em cảm ơn anh ạ!!!!

**Comment by vuthelinh** [comment]
Từ bản FF 55+ trở lên. Cộng đồng đã dừng phát triển Selenium IDE. Cho nên để sử dụng được selenium IDE trên FF em cần phải downgrade FF version xuống thấp hơn 55

https://seleniumhq.wordpress.com/
