### ISSUE TITLE
Tại sao có sự khác nhau khi in ra giá trị background- color ở các trình duyệt khác nhau

### ISSUE THREAD

**Issue by NTHang** [vuthelinh/selenium-vietnam-training-course#40]
Hi all
Em đang kiểm tra giá trị color nhưng khi in ra ở thì lại có sự khác nhau 
với trình duyệt firefox: rgb(255, 255, 255)
nhưng với trình duyệt chrome và IE là: rgba(255, 255, 255, 1)
Vì thế khi e dùng cách so sánh giá trị để kiểm tra pass failed gặp khó khăn  
Mọi người cho e xin ý kiến với ạ.
Thank all!

**Comment by vuthelinh** [comment]
Firefox thì sử dụng RGB còn ở kia là RGBA. thì rõ ràng nó thể hiện phải khác nhau. Nó phụ thuộc vào enginee của trình duyệt, về cơ bản giá trị nó không sai khác. Chỉ là khác nhau bảng màu thôi.

Với trường hợp như vậy thì có thể sử dụng if else.
