### ISSUE TITLE
Các loại wait trong selenium webdriver

### ISSUE THREAD

**Issue by rain301191** [vuthelinh/selenium-vietnam-training-course#6]
A linh làm video nói rõ hơn về các loại wait trong webdriver

**Comment by nguyendinhthuan789** [comment]
@vuthelinh   có video tham khảo ko anh :)

**Comment by vuthelinh** [comment]
Có em. Nhưng đây là phần câu hỏi của sinh viên lớp học. Ko public

**Comment by vuthelinh** [comment]
[How to use wait in webdriver](https://www.youtube.com/watch?v=c5w9TVtmhAo&list=PLpTCO0Fa9GR3FZG8uQTqIYIjMt1NAA-kZ&index=4)
