### ISSUE TITLE
Làm sao in kết quả tính toán vào trong report của serenity 

### ISSUE THREAD

**Issue by interpol2006** [vuthelinh/selenium-vietnam-training-course#7]

**Comment by vuthelinh** [comment]
Report của Serenity sẽ in ra các bước trong mục Steps của mô hình Page Object. Nó sẽ in các bước được đánh dấu bởi annotation @Test.

Bởi thế muốn in giá trị biến ngược lên trên report. Chỉ cần tạo một hàm in rồi gọi vào bên trong các steps này hoặc sử dụng trực tiếp nó as well

Ví dụ trong: Trong XXXSteps.java

@Test
public void i_need_print_out_value_to_report(){
    my_system_print_out(value);
    // more your steps here .....
}

@Test
public void my_system_print_out(String value){
     System.out.println(value);
}
