### ISSUE TITLE
Trong 1 feature có 10 scenarios, nếu muốn chạy 5 scenarios trong đó thì làm cách nào 

### ISSUE THREAD

**Issue by interpol2006** [vuthelinh/selenium-vietnam-training-course#8]

**Comment by vuthelinh** [comment]
Em đặt tag cho nó. Tất cả 5 scenarios đó có chung 1 tag
Ví dụ có cùng tag là demo
Thì chạy lệnh như sau
mvn verify -Dcucumber.options="--tags @demo"

Tham khảo thêm https://github.com/cucumber/cucumber/wiki/Tags
