### ISSUE TITLE
Review code

### ISSUE THREAD

**Issue by truyenkv** [vuthelinh/selenium-vietnam-training-course#9]
https://github.com/truyenkv/goodJob nhờ anh review code giúp e

**Comment by vuthelinh** [comment]
1. Sử dung giá trị của id hoặc name như là một đối tượng của WebElement.
ví dụ:
@FindBy(id="formControlsFirstName")
WebElement firstNameTxt;

 public void clear_First_Name() {
  firstNameTxt.clear();
 }
 public void input_First_Name(String fistNa) {
  firstNameTxt.sendKeys(fistNa);
}
Chúng ta viết gon lại là
WebElementFacade firstNameTxt

 public void input_First_Name(String fistNa) {
  typeInto(firstNameTxt, fistNa);
}
hoặc
firstNameTxt.type(fistNa)Hàm type trước khi nó enter value vào nó sẽ tự động empty cái filed trước. Nên không cần viết hàm clear()

**Comment by vuthelinh** [comment]
Làm việc với lệnh đối tượng của Action

```
Actions action = new Actions(getDriver());
action.moveToElement(userProfile).click().perform();
```
Thì có thể viết gọn lại là
`withAction().moveToElement(userProfile).click().perform();`

**Comment by vuthelinh** [comment]
Tên của một class thì nên bắt đầu bằng chữ HOA
Thay vì tên class là homePage hay loginPage thì nên đặt là HomePage và LoginPage

Tên của package thì nên dùng toàn bộ chữ thường. Thay vì goodJob thì nên là goodjob

**Comment by vuthelinh** [comment]
```
public void click_On_User() {
		WebDriverWait wait = new WebDriverWait(getDriver(), 10000);
		wait.until(ExpectedConditions.visibilityOf(logo));
		userIcon.click();
}
```
nên là
```
public void click_On_User() {
		logo.waitUntilVisible();
		userIcon.click();
}
```
